class NativeEngineTestPayloads {
  const NativeEngineTestPayloads._();

  static const List<Map<String, dynamic>> items = [
    {
      'title': 'Open Bible',
      'subtitle': 'Native engine: Bible',
      'engine': 'bible',
      'route': '/tools/bible',
      'type': 'tool',
    },
    {
      'title': 'Open Notes',
      'subtitle': 'Native engine: Notes',
      'engine': 'notes',
      'route': '/tools/notes',
      'type': 'tool',
    },
    {
      'title': 'Open Quote Creator',
      'subtitle': 'Native engine: Quote Creator',
      'engine': 'quote_creator',
      'route': '/tools/quote',
      'type': 'tool',
    },
    {
      'title': 'Daily Scripture → Bible',
      'subtitle': 'Bridge test: open Psalm 23:1 in Bible',
      'engine': 'bible',
      'type': 'daily-scripture',
      'source_type': 'daily-scripture',
      'source_id': 'daily_scripture_demo',
      'source_title': 'Daily Scripture',
      'reference': 'Psalm 23:1',
      'verse_reference': 'Psalm 23:1',
      'verse_text': 'The Lord is my shepherd; I shall not want.',
      'text': 'The Lord is my shepherd; I shall not want.',
    },
    {
      'title': 'Daily Scripture → Notes',
      'subtitle': 'Bridge test: create note with scripture',
      'engine': 'notes',
      'type': 'daily-scripture',
      'source_type': 'daily-scripture',
      'source_id': 'daily_scripture_demo',
      'source_title': 'Daily Scripture',
      'reference': 'Psalm 23:1',
      'verse_reference': 'Psalm 23:1',
      'verse_text': 'The Lord is my shepherd; I shall not want.',
      'note_text': 'Psalm 23:1 — The Lord is my shepherd; I shall not want.',
      'text': 'Psalm 23:1 — The Lord is my shepherd; I shall not want.',
    },
    {
      'title': 'Daily Scripture → Quote Creator',
      'subtitle': 'Bridge test: make quote from scripture',
      'engine': 'quote_creator',
      'type': 'daily-scripture',
      'source_type': 'daily-scripture',
      'source_id': 'daily_scripture_demo',
      'source_title': 'Psalm 23:1',
      'reference': 'Psalm 23:1',
      'verse_reference': 'Psalm 23:1',
      'verse_text': 'The Lord is my shepherd; I shall not want.',
      'quote_text': 'The Lord is my shepherd; I shall not want.',
      'text': 'The Lord is my shepherd; I shall not want.',
    },
    {
      'title': 'Daily Quote → Notes',
      'subtitle': 'Bridge test: save quote into notes',
      'engine': 'notes',
      'type': 'daily-quote',
      'source_type': 'daily-quote',
      'source_id': 'daily_quote_demo',
      'source_title': 'Daily Quote',
      'note_text': 'Faith becomes stronger when it is exercised daily.',
      'text': 'Faith becomes stronger when it is exercised daily.',
    },
    {
      'title': 'Daily Quote → Quote Creator',
      'subtitle': 'Bridge test: design daily quote',
      'engine': 'quote_creator',
      'type': 'daily-quote',
      'source_type': 'daily-quote',
      'source_id': 'daily_quote_demo',
      'source_title': 'Daily Quote',
      'quote_text': 'Faith becomes stronger when it is exercised daily.',
      'text': 'Faith becomes stronger when it is exercised daily.',
    },
    {
      'title': 'Article Text → Notes',
      'subtitle': 'Bridge test: selected article text into note',
      'engine': 'notes',
      'type': 'article',
      'source_type': 'article',
      'source_id': 'article_demo',
      'source_title': 'Article Highlight',
      'note_text': 'This is a selected article line saved for later meditation.',
      'text': 'This is a selected article line saved for later meditation.',
    },
    {
      'title': 'Article Text → Quote Creator',
      'subtitle': 'Bridge test: selected article text into quote designer',
      'engine': 'quote_creator',
      'type': 'article',
      'source_type': 'article',
      'source_id': 'article_demo',
      'source_title': 'Article Highlight',
      'quote_text': 'This is a selected article line saved for later meditation.',
      'text': 'This is a selected article line saved for later meditation.',
    },
    {
      'title': 'Section Test: Scripture Auto Actions',
      'subtitle': 'No engine defined → section fallback payload test',
      'type': 'scripture',
      'section_key': 'test_scripture',
      'source_type': 'daily_scripture',
      'verse_text': 'The Lord is my shepherd; I shall not want.',
      'reference': 'Psalm 23:1',
    },
    {
      'title': 'Open Web Page',
      'subtitle': 'Native engine: Web',
      'engine': 'web',
      'url': 'https://dunamisgospel.org',
      'type': 'web',
    },
    {
      'title': 'Open YouTube Player',
      'subtitle': 'Native engine: YouTube',
      'engine': 'youtube',
      'url': 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      'type': 'video',
    },
    {
      'title': 'Open HLS Player',
      'subtitle': 'Native engine: HLS',
      'engine': 'hls',
      'url': 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
      'type': 'live',
    },
    {
      'title': 'Open Article Detail',
      'subtitle': 'Native engine: Article',
      'engine': 'article',
      'content_id': 'demo',
      'id': 'demo',
      'type': 'article',
    },
    {
      'title': 'Open Shorts',
      'subtitle': 'Native engine: Shorts',
      'engine': 'shorts',
      'type': 'shorts',
    },
    {
      'title': 'Future Engine: Store',
      'subtitle': 'Reserved future native engine',
      'engine': 'store',
      'type': 'future',
      'app_type': 'store',
    },
    {
      'title': 'Future Engine: Podcast',
      'subtitle': 'Reserved future native engine',
      'engine': 'podcast',
      'type': 'future',
    },
    {
      'title': 'Future Engine: Music',
      'subtitle': 'Reserved future native engine',
      'engine': 'music',
      'type': 'future',
    },
  ];
}
